[2023-06-07 09:46:36,134][src.utils][INFO] - Git sha: a78aae517535a9760211e71ffc591118b750a75c
[2023-06-07 09:46:36,152][src.utils][INFO] - Changed files: ['src/evals/sequence_completion.py']
[2023-06-07 09:46:36,168][src.utils][INFO] - Git diff:
diff --git a/src/evals/sequence_completion.py b/src/evals/sequence_completion.py
index a44cbe6..27c3ac5 100644
--- a/src/evals/sequence_completion.py
+++ b/src/evals/sequence_completion.py
@@ -149,10 +149,10 @@ def sequence_completion_equality(
             "sequence": sequence,
             "generated_completion_rule": explanation,
             "generated_completion": actual_completion,
-            "generated_completion_matches": None,
+            "generated_completion_matches": False,
             "model_self_consistency_evaluation": consistency_resp,
             "model_completion": model_completion_resp,
-            "model_completion_matches": None,
+            "model_completion_matches": False,
         }

     last_completion = eval(explanation)(last_completion_step + 1)
[2023-06-07 09:46:36,170][src.utils][INFO] - Changed directory to /Users/domenicrosati/src/introspective-self-consistency/results/2023-06-07-09-46-35/compute_dependence_with_base_changes=False,sequence_completion_capability.model=text-davinci-003,sequence_completion_equality=False,string_transformation_completion_equality=False/evaluate_sequence_completion_capability
[2023-06-07 09:46:36,170][src.evals.sequence_completion_capability][INFO] - Evaluating sequence completion capability...
[2023-06-07 09:46:53,729][src.evals.sequence_completion_capability][ERROR] - 0.0 cannot be raised to a negative power
Traceback (most recent call last):
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 110, in evaluate_sequence_completion_capability
    sequence_completion_eval(
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 69, in sequence_completion_eval
    completion = eval(explanation)(i)
  File "<string>", line 1, in <lambda>
ZeroDivisionError: 0.0 cannot be raised to a negative power
[2023-06-07 09:46:53,732][src.evals.sequence_completion_capability][WARNING] - 0.0 cannot be raised to a negative power
[2023-06-07 09:47:41,550][src.evals.sequence_completion_capability][ERROR] - name 'reduce' is not defined
Traceback (most recent call last):
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 110, in evaluate_sequence_completion_capability
    sequence_completion_eval(
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 69, in sequence_completion_eval
    completion = eval(explanation)(i)
  File "<string>", line 1, in <lambda>
NameError: name 'reduce' is not defined
[2023-06-07 09:47:41,551][src.evals.sequence_completion_capability][WARNING] - name 'reduce' is not defined
[2023-06-07 09:48:58,145][src.evals.sequence_completion_capability][ERROR] - 0.0 cannot be raised to a negative power
Traceback (most recent call last):
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 110, in evaluate_sequence_completion_capability
    sequence_completion_eval(
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 69, in sequence_completion_eval
    completion = eval(explanation)(i)
  File "<string>", line 1, in <lambda>
ZeroDivisionError: 0.0 cannot be raised to a negative power
[2023-06-07 09:48:58,146][src.evals.sequence_completion_capability][WARNING] - 0.0 cannot be raised to a negative power
[2023-06-07 09:49:13,505][src.evals.sequence_completion_capability][ERROR] - 0.0 cannot be raised to a negative power
Traceback (most recent call last):
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 110, in evaluate_sequence_completion_capability
    sequence_completion_eval(
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 69, in sequence_completion_eval
    completion = eval(explanation)(i)
  File "<string>", line 1, in <lambda>
ZeroDivisionError: 0.0 cannot be raised to a negative power
[2023-06-07 09:49:13,505][src.evals.sequence_completion_capability][WARNING] - 0.0 cannot be raised to a negative power
[2023-06-07 09:49:20,980][src.evals.sequence_completion_capability][ERROR] - 0.0 cannot be raised to a negative power
Traceback (most recent call last):
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 110, in evaluate_sequence_completion_capability
    sequence_completion_eval(
  File "/Users/domenicrosati/src/introspective-self-consistency/src/evals/sequence_completion_capability.py", line 69, in sequence_completion_eval
    completion = eval(explanation)(i)
  File "<string>", line 1, in <lambda>
ZeroDivisionError: 0.0 cannot be raised to a negative power
[2023-06-07 09:49:20,980][src.evals.sequence_completion_capability][WARNING] - 0.0 cannot be raised to a negative power
[2023-06-07 09:50:05,723][src.evals.sequence_completion_capability][INFO] -
        Evaluated 134 ambiguous sequences of 139 total.
        Resulting in:
        - 37.0% rules_matches_sequence
        - 72.0% completion_is_correct
